FROM adoptopenjdk/openjdk8:alpine-slim

MAINTAINER ayesh almeida

COPY ./target/docker-sample-app /opt/app

RUN chmod 777 /opt/app/bin/*

WORKDIR /opt/app/bin/

RUN ls -l ./

CMD ["sh", "docker-sample-app", "console"]

EXPOSE 10001
